meta_title: "Caddy Connect"
meta_description: "Garder un Oeil sur vos Commandes en ligne"
meta_image: "caddy-connect-ban.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@manoufeb" # indispensable pour les Twitter Cards